### ISSUE TITLE
0.2.3 had breaking change

### ISSUE THREAD

**Issue by hlthi** [tmcw/geojson-flatten#13]
I start by thanking you for all your labor,

This is interesting issue, I'm going to have a little trouble explaining.

```javascript
// 0.2.1 -> https://github.com/tmcw/geojson-flatten/archive/v0.2.3.zip > index.js
...function flatten(gj)
... module.exports = flatten
```

```javascript
// it works.
var bar = require("foo")
```
But,

```javascript
// 0.2.3 -> https://github.com/tmcw/geojson-flatten/archive/v0.2.3.zip > index.js
... export default function flatten(gj)
```
```javascript
// it doesn't works.
var bar = require("foo")  
```

We have to write like,
```javascript
var bar = require("foo").default,
```
 [Source](https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6)

This is breaking change. mapbox/geojson-coords working correctly but, mapbox/mapbox-gl-draw doesn't work with that (Maybe babel , uglifyjs, or something else).

This library using in geojson-coords, geojson-coords using in mapbox-gl-draw.

mapbox/geojson-coords have these lines in package.json

```javascript
 "geojson-flatten": "~0.2.1"
```

If "yarn upgrade" or npm equivalent, geojson-flatten goes up 0.2.3 and everything is break.

0.2.3 version can be deleted npm and this repo's release.

**Comment by tmcw** [comment]
Thanks for the report!

I have some doubts about this one. The contents of `index.js` certainly changed, but the specific file layout of a module shouldn't matter: what matter is what's referred to in `package.json`. The `main` entry changed, in 0.2.3, from `index.js` to `dist/index.js`. `index.js` has ES Module syntax, but `dist/index.js` has CommonJS syntax, and is backwards-compatible with the previous entry point.

So, the valid ways to use this module are:

- Use `require()`, which uses `main`. This is what Node would do, and browserify.
- Use `import ""`, which uses `module`. This is what rollup, webpack, or a browser would do.

If you test geojson-coords, for example, and update to 0.2.3, the tests pass. geojson-coords is correctly using the `main` entry to get a CommonJS entry point.

The behavior that you describe would happen if:

- It was specifying the `index.js` file, like `require('geojson-flatten/index')`. This would violate semver on its side.
- Its build process was automatically choosing the `module` entry point for `require()`. This would be not recommended.

The gist is, this module, in terms of consistently exposing the correct entry points, does not have any breaking change that I can see. I strongly suspect that mapbox-gl-draw is making one of the mistakes listed above, which is causing the breakage, and short of 'not providing a module entry point', there's now way for me to fix the problem.

Happy to hear any other details that narrow down the cause of this problem.

**Comment by gpanneti** [comment]
Hello !
I'm having an issue using @mapbox/coords since the 0.2.3 update. Because @mapbox/coords use  `require('geosjon-flatten')` instead of `require('geojson-flatten).defualt` it's breaking my application.

To me, this is a major change.

**Comment by hlthi** [comment]
Hey @gpanneti , if you use yarn add this block to package.json,
```
"resolutions": {
    "geojson-flatten": "0.2.1"
  },
```
For ensure delete yarn.lock and node_modules, and yarn install.

So you can be sure that 0.2.1 is used always. This solution is currently in use production.
You can check lock file to make sure.

Dont edit lock file, just use resolution,delete lock and node_modules,and yarn install. Everything will be fine.
```
geojson-flatten@0.2.1, geojson-flatten@~0.2.1:
  version "0.2.1"
  resolved "https://registry.yarnpkg.com/geojson-flatten/-/geojson-flatten-0.2.1.tgz#476fc6b041e94d016983ec95400f8777bd60c45c"
  integrity sha1-R2/GsEHpTQFpg+yVQA+Hd71gxFw=
  dependencies:
    concat-stream "~1.2.1"
    minimist "0.0.5"
```

[Yarn documentation for resolution (tested)](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it)
[NPM equivalent for yarn resolution (not tested)](https://docs.npmjs.com/cli/shrinkwrap)

**Comment by hlthi** [comment]
@tmcw gave really good answer. All tests is ok.

For me , I used create-react-app with typescript and mapbox-gl-js. Browserify, webpack , typescript or something else may have caused this. Drawing polygon really edge case for some application, I think so many project affected this situation. No one's noticed yet, we're two with you @gpanneti . I think our numbers will increase.

**Comment by gpanneti** [comment]
> Hey @gpanneti , if you use yarn add this block to package.json,
> 
> ```
> "resolutions": {
>     "geojson-flatten": "0.2.1"
>   },
> ```
> For ensure delete yarn.lock and node_modules, and yarn install.
> 
> So you can be sure that 0.2.1 is used always. This solution is currently in use production.
> You can check lock file to make sure.
> 
> Dont edit lock file, just use resolution,delete lock and node_modules,and yarn install. Everything will be fine.
> 
> ```
> geojson-flatten@0.2.1, geojson-flatten@~0.2.1:
>   version "0.2.1"
>   resolved "https://registry.yarnpkg.com/geojson-flatten/-/geojson-flatten-0.2.1.tgz#476fc6b041e94d016983ec95400f8777bd60c45c"
>   integrity sha1-R2/GsEHpTQFpg+yVQA+Hd71gxFw=
>   dependencies:
>     concat-stream "~1.2.1"
>     minimist "0.0.5"
> ```
> [Yarn documentation for resolution (tested)](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it)
> [NPM equivalent for yarn resolution (not tested)](https://docs.npmjs.com/cli/shrinkwrap)

Thanks @hlthi ! I'm using npm and I didn't commit package-lock.json until now because had some problems with it, but I think I will be forced to do it now.

I'm gonna try.

**Comment by tmcw** [comment]
@gpanneti what are you using as a bundler? Webpack, browserify, something else? Knowing what the actual projects are that _consume_ these modules are is useful, because it has been, so far, impossible to isolate any issue in the projects themselves.

**Comment by tmcw** [comment]
Upstream in create-react-app: https://github.com/facebook/create-react-app/issues/6321
