### ISSUE TITLE
Passing a feature with null geometry returns a feature, not an array

### ISSUE THREAD

**Issue by stevage** [tmcw/geojson-flatten#26]
```
var geojsonFlatten = require("geojson-flatten")
console.log(geojsonFlatten({"type":"Feature","properties":{},"geometry":null}))
console.log(geojsonFlatten({"type":"Feature","properties":{},"geometry":{type:'Point',coordinates:[0,0]}}))


Object {geometry: null, properties: Object {}, type: "Feature"}
[Object {geometry: Object {coordinates: [0, 0], type: "Point"}, properties: Object {}, type: "Feature"}]
```

I'm not exactly sure what the correct behaviour should be, but it feels unintuitive (and messed up a long-running script for me) that the type of the return (object vs array) depends on whether or not the feature has geometry.

Probably it should just return an array in both cases?

Want a PR for this?

**Comment by tmcw** [comment]
Yep, looks like

https://github.com/tmcw/geojson-flatten/blob/master/index.js#L9

Needs to return the feature rather than returning gj.
