### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by bigfacewo** [tmcw/geojson-flatten#34]
If there is no properties object in my geojson, it will be reported JSON.parse Error. The reason is that the [code](https://github.com/tmcw/geojson-flatten/blob/master/index.js#L13) does not handle the case that properties are empty.

**Comment by tmcw** [comment]
Valid values for `properties` are either an object, or `null`. Omitting the properties member from a Feature object makes GeoJSON invalid. https://tools.ietf.org/html/rfc7946#section-3.2
