### ISSUE TITLE
Move geojson-flatten executable into a separate package

### ISSUE THREAD

**Issue by ThisIsMissEm** [tmcw/geojson-flatten#45]
Currently this package gets warnings via dependency vulnerability scanning tools because of depending on CLI oriented packages, e.g., minimist, when the packages' actual code doesn't actually use those dependencies directly.

It'd be an idea to split this package in two: `geojson-flatten` and `geojson-flatten-cli` or something similar, as to not have these misleading security issues (also, it's common to only install this module as a dependency of a project using mapbox, rather than needing the CLI tool).

**Comment by tmcw** [comment]
Yep, that's a good idea! Did the same with togeojson and it worked well.
